services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    external: true
